### ISSUE TITLE
请问如何用VLLM部署33B

### ISSUE THREAD

**Issue by laisun** [deepseek-ai/DeepSeek-Coder#27]
会报错啊，单机A100 ，torch 2.01， transformers 4.35
    key = torch.repeat_interleave(key, self.num_queries_per_kv, dim=1)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by soloice** [comment]
单机 A100 是几张卡？打开 CUDA_LAUNCH_BLOCKING=1 试试呢，报错在哪里？

**Comment by cdj0311** [comment]
我也遇到同样的问题

**Comment by FrankWhh** [comment]
我部署后输出是乱码，有人遇到过吗

**Comment by txy6666yr** [comment]
> 单机 A100 是几张卡？打开 CUDA_LAUNCH_BLOCKING=1 试试呢，报错在哪里？

请问有vllm部署的教程吗？或者文件分享下文件

**Comment by hyperbolic-c** [comment]
请问vllm部署时如何使用多卡加载模型，使用`CUDA_VISIBLE_DEVICES=0,1`还是只有一张卡load了， 很奇怪，谢谢

**Comment by mklf** [comment]
> 请问vllm部署时如何使用多卡加载模型，使用`CUDA_VISIBLE_DEVICES=0,1`还是只有一张卡load了， 很奇怪，谢谢

try add `--tp=2` to launch argument

**Comment by hyperbolic-c** [comment]
> > 请问vllm部署时如何使用多卡加载模型，使用`CUDA_VISIBLE_DEVICES=0,1`还是只有一张卡load了， 很奇怪，谢谢
> 
> try add `--tp=2` to launch argument

thanks, I have solved it by set `--tensor-parallel-size` >1.
